# Python Packages

In [2]:
import warnings
warnings.filterwarnings('ignore')

## 1. numpy
- 수학 및 과학적 연산을 쉽고 빠르게 지원
- 다차원 행열(Array)을 효과적으로 처리

### 1) numpy Package import

In [4]:
import numpy as np

### 2) Array 생성
#### (1) Scalar - 0D Array - Rank0 Tensor
- Rank:'축'을 의미

In [5]:
a0 = np.array(9)
# 하나의 데이터(data point)
print(a0)

9


#### (2) Vector - 1D Array - Rank1 Tensor

- 파이썬의 리스트를 np의 array로 캐스팅

In [6]:
a1 = np.array([1, 3, 5, 7, 9])
print(a1)



[1 3 5 7 9]


In [7]:
a1

# print 를 지워보면, array 로 표시됨
# array: 데이터를 설명하기 위한 추가 데이터 (메타데이터)
# type이 list 가 아니라 np.array

array([1, 3, 5, 7, 9])

#### (3) Matrix - 2D Array - Rank2 Tensor

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### (4) Array - 3D Array - Rank3 Tensor

In [12]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])

print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### 3) AR.shape and AR.reshape()

In [13]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### (1) .shape

In [14]:
AR.shape

(12,)

#### .reshape(행,열)

In [15]:
AR2 = AR.reshape(3,4)
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
AR2.shape

(3, 4)

#### (3) .reshape(축, 행, 열)

In [17]:
AR3 = AR.reshape(3, 2, 2)
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [18]:
AR3.shape

(3, 2, 2)

### 4) 범위지정(arange) 함수 사용
(1) 10개의 연속된 값 생성

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

(2) 1부터 9까지 1 간격으로 생성

In [20]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

(3) 1부터 9까지 2 간격으로 생성

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

(4) 생성된 Array에 .reshape() 적용

In [22]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 5) 특별한 형태의 Array 생성
#### (1) 0과 1로만 구성된 Array

In [23]:
# tensorflow는 float만 받는다
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### (2) 3 * 3 단위행렬

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### (3) 난수 Array 생성

In [28]:
# rand : 0~1 사이 무작위

np.random.rand(3, 2, 2)

array([[[0.97162993, 0.57382965],
        [0.46193608, 0.93605699]],

       [[0.4472054 , 0.58161014],
        [0.7829851 , 0.91393195]],

       [[0.96208667, 0.97533405],
        [0.92426734, 0.0459116 ]]])

In [29]:
# randint : 복원추출함(겹침)
np.random.randint(1, 45, size = (5, 6))

array([[40, 20, 18,  7,  3,  1],
       [15,  3, 41, 24, 27, 31],
       [31, 24, 43, 30, 34, 25],
       [25, 43, 32, 10, 17, 14],
       [17, 44, 31, 26, 34, 21]])

In [30]:
np.random.seed(2045) # 실험의 복원

# random.choice replace=False(비복원추출)를 사용하면 겹치지 않음

np.random.choice(np.arange(1, 46), size = (5, 6), replace=False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

### 6) Array 연산

In [31]:
a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([10, 30, 50, 70, 90])

#### (1) 기본연산

In [32]:
a1 + a2

array([11, 33, 55, 77, 99])

In [33]:
a2 - a1

array([ 9, 27, 45, 63, 81])

In [34]:
a1 * a2

array([ 10,  90, 250, 490, 810])

In [35]:
a2 / a1

array([10., 10., 10., 10., 10.])

In [36]:
a1 ** 2 # 브로드캐스트 연산

array([ 1,  9, 25, 49, 81])

#### (2) 통계량 연산
- 총합

In [37]:
a1.sum()

25

- 평균

In [38]:
a2.mean()

50.0

- 표준편차

In [39]:
a2.std()

28.284271247461902

- 최소값

In [40]:
a2.min()

10

- 최대값

In [41]:
a2.max()

90

- 누적합(Cumulative)

In [42]:
a1.cumsum()

array([ 1,  4,  9, 16, 25])

- 누적곱(Cumulative)

In [43]:
a1.cumprod()

array([  1,   3,  15, 105, 945])

### 7) Matrix 연산
- A1, A2지정

In [44]:
A1 = np.array([2,4,6,8]).reshape(2,2)
print(A1)

[[2 4]
 [6 8]]


In [45]:
A2 = np.array([3,5,7,9]).reshape(2,2)
print(A2)

[[3 5]
 [7 9]]


#### (1) Matrix 곱 - A1 @ A2
- A1 @ A2

In [46]:
A1.dot(A2)

array([[ 34,  46],
       [ 74, 102]])

- A2 @ A1

In [47]:
np.dot(A2, A1)

array([[ 36,  52],
       [ 68, 100]])

- Warning: A1 * A2

In [48]:
A1 * A2

array([[ 6, 20],
       [42, 72]])

#### (2) 전치행렬
- A1의 전치행렬

In [49]:
np.transpose(A1)

array([[2, 6],
       [4, 8]])

- A2의 전치행렬

In [50]:
A2.transpose()

array([[3, 7],
       [5, 9]])